<?php

namespace Loonins\IncidentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GdpMailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GdpMailsRepository extends EntityRepository
{
}
