<?php

namespace Loonins\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimatriceRepository extends EntityRepository
{
}
