<?php

namespace Loonins\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginAnimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAnimRepository extends EntityRepository
{
}
