<?php

namespace Loonins\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTableRepository extends EntityRepository
{
}
