# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SAR:       ROLE_USER
        ROLE_GRH:       [ROLE_GRH, ROLE_SAR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER,ROLE_GRH, ROLE_SAR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    # access_control:
    #     - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin/, role: ROLE_ADMIN }
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#Mode developpement
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#Mode production
#       - { path: ^/register, roles: [ROLE_ADMIN] }

        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/grhemployes/anniversaire, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/grhalert, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/alert/mail/contrat/delai/E/21, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/alert/mail/contrat/delai/E/14, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/alert/mail/contrat/delai/E/7, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/alert/mail/contrat/delai/E/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/wishes/christams, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/wishes/newyear, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grh/terminate/contrat, role: IS_AUTHENTICATED_ANONYMOUSLY }

        
        - { path: ^/grh/grh/repertoire$, role: ROLE_USER }
        - { path: ^/sar/load/excel, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sar/rech, role: ROLE_USER }
        - { path: ^/sar/anim/, role: ROLE_USER }
        - { path: ^/sar/cumul/, role: ROLE_USER }
        - { path: ^/sar/both, role: ROLE_USER }
              
        - { path: ^/group, role: ROLE_SUPER_ADMIN }
        - { path: ^/wiki/categorie, roles: [ROLE_ADMIN] }
        - { path: ^/wiki/rubrique, roles: [ROLE_ADMIN] }
        - { path: ^/wiki/article, roles: [ROLE_USER ] }
        - { path: ^/wiki/, roles: [ROLE_USER] }
        - { path: ^/gdp, roles: [ROLE_USER] }
        - { path: ^/grh/, roles: [ROLE_GRH] }
        - { path: ^/sar/, roles: [ROLE_SAR] }
        - { path: ^/suivi/, roles: [ROLE_GRH] }
#        - { path: ^/grh^, roles: [ROLE_ADMIN] }
        - { path: ^/profile/show, roles: ROLE_USER }
        
        









# # To get started with security, check out the documentation:
# # http://symfony.com/doc/current/book/security.html
# security:

#     # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         # disables authentication for assets and the profiler, adapt it according to your needs
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         main:
#             anonymous: ~
#             # activate different ways to authenticate

#             # http_basic: ~
#             # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

#             # form_login: ~
#             # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
