loonins_suivi_homepage:
    path:  /hello/{name}
    defaults: { _controller: LooninsSuiviBundle:Default:index }

suivi_stat:
    path:  /suivi/
    defaults: { _controller: LooninsSuiviBundle:Stat:search }
    requirements:
        _method:  GET

typetable:
    path:  /typetable
    defaults: { _controller: LooninsSuiviBundle:TypeTable:index }
    requirements:
        _method:  GET

typetable_new:
    path:  /typetable/new
    defaults: { _controller: LooninsSuiviBundle:TypeTable:new }
    requirements:
        _method:  GET

typetable_create:
    path:  /typetable/create
    defaults: { _controller: LooninsSuiviBundle:TypeTable:create }
    requirements:
        _method:  POST

typetable_show:
    path:  /typetable/show/{id}
    defaults: { _controller: LooninsSuiviBundle:TypeTable:show }
    requirements:
        _method:  GET

typetable_edit:
    path:  /typetable/edit/{id}
    defaults: { _controller: LooninsSuiviBundle:TypeTable:edit }
    requirements:
        _method:  GET

typetable_update:
    path:  /typetable/update/{id}
    defaults: { _controller: LooninsSuiviBundle:TypeTable:update}
    requirements:
        _method:  POST

typetable_delete:
    path:  /typetable/delete/{id}
    defaults: { _controller: LooninsSuiviBundle:TypeTable:delete }
    requirements:
        _method:  POST|PUT







animatrice:
    path:  /animatrice
    defaults: { _controller: LooninsSuiviBundle:Animatrice:index }
    requirements:
        _method:  GET

animatrice_new:
    path:  /animatrice/new
    defaults: { _controller: LooninsSuiviBundle:Animatrice:new }
    requirements:
        _method:  GET

animatrice_create:
    path:  /animatrice/create
    defaults: { _controller: LooninsSuiviBundle:Animatrice:create }
    requirements:
        _method:  POST

animatrice_show:
    path:  /animatrice/show/{id}
    defaults: { _controller: LooninsSuiviBundle:Animatrice:show }
    requirements:
        _method:  GET

animatrice_edit:
    path:  /animatrice/edit/{id}
    defaults: { _controller: LooninsSuiviBundle:Animatrice:edit }
    requirements:
        _method:  GET

animatrice_update:
    path:  /animatrice/update/{id}
    defaults: { _controller: LooninsSuiviBundle:Animatrice:update}
    requirements:
        _method:  POST

animatrice_delete:
    path:  /animatrice/delete/{id}
    defaults: { _controller: LooninsSuiviBundle:Animatrice:delete }
    requirements:
        _method:  POST|PUT

animatrice_suppr:
    path:  /animatrice/suppr/{id}
    defaults: { _controller: LooninsSuiviBundle:Animatrice:suppr }
    requirements:
        _method:  GET

stat:
    path:  /stat
    defaults: { _controller: LooninsSuiviBundle:Stat:index }
    requirements:
        _method:  GET|POST

stat_search:
    path:  /rech
    defaults: { _controller: LooninsSuiviBundle:Stat:search }
    requirements:
        _method:  GET|POST

post_to_stat_search:
    path:  /reches
    defaults: { _controller: LooninsSuiviBundle:Stat:search }
    requirements:
        _method:  POST

stat_cumul_one:
    path:  /cumul/one/{busdt1}/{busdt2}/{type}/{animatrice}
    defaults: { _controller: LooninsSuiviBundle:Stat:cumulone }
    requirements:
        _method:  GET

stat_new:
    path:  /stat/new
    defaults: { _controller: LooninsSuiviBundle:Stat:new }
    requirements:
        _method:  GET

stat_export:
    path:  /stat/export
    defaults: { _controller: LooninsSuiviBundle:Stat:export }
    requirements:
        _method:  GET

stat_create:
    path:  /stat/create
    defaults: { _controller: LooninsSuiviBundle:Stat:create }
    requirements:
        _method:  POST

stat_show:
    path:  /stat/show/{table}/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:show }
    requirements:
        _method:  GET

stat_edit:
    path:  /stat/edit/{id}/{from}
    defaults: { _controller: LooninsSuiviBundle:Stat:edit }
    requirements:
        _method:  GET

stat_edit_details:
    path:  /stat/edit/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:editDetails }
    requirements:
        _method:  GET

stat_view:
    path:  /stat/view/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:view }
    requirements:
        _method:  GET

stat_details:
    path:  /stat/details/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:view }
    requirements:
        _method:  GET

stat_update:
    path:  /stat/update/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:update}
    requirements:
        _method:  POST

stat_details_update:
    path:  /stat/update/details/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:updateDetails}
    requirements:
        _method:  POST

stat_delete:
    path:  /stat/delete/{id}
    defaults: { _controller: LooninsSuiviBundle:Stat:delete }
    requirements:
        _method:  POST|PUT


tech:
    path:  /journal
    defaults: { _controller: LooninsSuiviBundle:Journal:index }
    requirements:
        _method:  GET

tech_end:
    path:  /journal/end/{stat}
    defaults: { _controller: LooninsSuiviBundle:Journal:end }
    requirements:
        _method:  GET

journal_export:
    path:  /journal/export
    defaults: { _controller: LooninsSuiviBundle:Journal:export }
    requirements:
        _method:  GET