parameters:
#    loonins_incident.example.class: Loonins\IncidentBundle\Example

services:
#    loonins_incident.example:
#        class: %loonins_incident.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
