<?php

namespace Loonins\GrhBundle\Repository;

/**
 * GrhMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrhMailRepository extends \Doctrine\ORM\EntityRepository
{
}
