parameters:
#    loonins_wiki.example.class: Loonins\WikiBundle\Example

services:
#    loonins_wiki.example:
#        class: %loonins_wiki.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
