<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * AffectLoginNeguitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectLoginNeguitRepository extends \Doctrine\ORM\EntityRepository
{
}
