<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * AffectFantomeNeguitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectFantomeNeguitRepository extends \Doctrine\ORM\EntityRepository
{
}
