<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * LoginAnimNeguitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAnimNeguitRepository extends \Doctrine\ORM\EntityRepository
{
}
