<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * PlanningPVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningPVRepository extends \Doctrine\ORM\EntityRepository
{
}
