<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * ProfilVirtuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilVirtuelRepository extends \Doctrine\ORM\EntityRepository
{
}
