<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * TypeAnimNeguitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnimNeguitRepository extends \Doctrine\ORM\EntityRepository
{
}
