<?php

namespace Loonins\NeguitBundle\Repository;

/**
 * TypeAnimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnimRepository extends \Doctrine\ORM\EntityRepository
{
}
