<?php

namespace Loonins\GesCongeBundle\Repository;

/**
 * DemandeCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCongeRepository extends \Doctrine\ORM\EntityRepository
{
}
