<?php

namespace Loonins\GesCongeBundle\Repository;

/**
 * SoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeRepository extends \Doctrine\ORM\EntityRepository
{
}
