<?php

namespace Loonins\GesCongeBundle\Repository;

/**
 * TypeDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
