<?php

namespace Loonins\GrhBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Loonins\GrhBundle\Entity\GrhEmployes;
use Symfony\Bundle\FrameworkBundle\Controller\Controller as Ctrl;
/**
 * GrhEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrhEmployeRepository extends EntityRepository {
//    function __construct() {
//        $this->_entityName = 'GrhEmployes';
//        $ctrl = new Ctrl();
//        $this->_entityName = $ctrl->getDoctrine()->getManager();
//        $this->_class = new \Doctrine\ORM\Mapping\ClassMetadata($this->_entityName);
//    }
    public static function floodContrat($employe) {
//        $em = $this->getDoctrine()->getManager();
//        $query = $em->createQueryBuilder();
//        $query
//                ->select('c')
//                ->from('LooninsGrhBundle:GrhContrats', 'c')
//                ->where("c.employes = :employe")
//                ->where("c.status != 3")
//                ->andwhere("c.status != 4")
//                ->setParameter('employe', $employe->getId());
        return $entities = array();//$query->getQuery()->getResult();
    }

}
