<?php

namespace Loonins\GrhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrhFicheSalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrhFicheSalarieRepository extends EntityRepository
{
}
