<?php

namespace Loonins\GrhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrhParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrhParamsRepository extends EntityRepository
{
}
