<?php

namespace Loonins\CalendarBundle\Repository;

/**
 * PlanningCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningCongeRepository extends \Doctrine\ORM\EntityRepository
{
}
