<?php

namespace Loonins\CalendarBundle\Repository;

/**
 * PlanningHebdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningHebdoRepository extends \Doctrine\ORM\EntityRepository
{
}
