<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * ActivitePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitePlanRepository extends \Doctrine\ORM\EntityRepository
{
}
