<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * AffectationLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
