<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * AliasActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
