<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * DemandeExplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeExplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
