<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * EnvoiDERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvoiDERepository extends \Doctrine\ORM\EntityRepository
{
}
