<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * ExcelPlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcelPlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
