<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * JourPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
