<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * LoginAnimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAnimRepository extends \Doctrine\ORM\EntityRepository
{
}
