<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * PanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanningRepository extends \Doctrine\ORM\EntityRepository
{
}
