<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * RespMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespMailRepository extends \Doctrine\ORM\EntityRepository
{
}
