<?php

namespace Loonins\SuiviBundle\Repository;

/**
 * SemPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
